task: sst2
model_name: tokenizer_gpt2
pretrained_ckpt: ./checkpoints/gpt1_tokenizer_gpt2/best.pt
tokenizer_path: ./data/tokenizer_gpt2
train_file: ./data/sst2/train.jsonl
valid_file: ./data/sst2/validation.jsonl
block_size: 128
max_length: 128
batch_size: 16
eval_batch_size: 32
epochs: 3
lr: 6.25e-5
weight_decay: 0.01
warmup_ratio: 0.002
grad_clip: 1.0
seed: 42
save_dir: ./checkpoints/sst2_tokenizer_gpt2
num_workers: 0
